### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by talatccan** [susantabiswas/Word-Prediction-Ngram#1]
Hi,

There is no corpusfile.txt so i tried to test my txt file. First i get encoding error and i fixed it by adding encoding='utf-8' into loadCorpus.

Now i get another error. Its list index out of range.  How can i fix it?

```
IndexError                                Traceback (most recent call last)
<ipython-input-17-c7bc734e5e35> in <module>()
      1 if __name__ == '__main__':
----> 2     main()

<ipython-input-16-abe7438bdb9e> in main()
     12     train_file = 'corpusfile.txt'
     13     #load the corpus for the dataset
---> 14     token_len = loadCorpus(train_file, bi_dict, tri_dict, quad_dict, vocab_dict)
     15 
     16     #estimate the lambdas for interpolation

<ipython-input-3-47bb9304cafa> in loadCorpus(file_path, bi_dict, tri_dict, quad_dict, vocab_dict)
     97 
     98             #store the last few words for the next sentence pairing
---> 99             w1 = token[n -3]
    100             w2 = token[n -2]
    101             w3 = token[n -1]

IndexError: list index out of range
```

**Comment by susantabiswas** [comment]
make sure that the corpus you are using has more than 3 words, I reran the code for Add-1 smoothing to check and it worked fine.

**Comment by talatccan** [comment]
Thank you for fast reply.

Are you meaning that, every line should have more than 3 words? Because my .txt file is very big.

**Comment by susantabiswas** [comment]
This error was raised when there were less than 3 tokens available at a particular instant. I have made changes to to the code to fix this, you can check that out.  #bug_fix

**Comment by ShrikanthSingh** [comment]
May I know the reason for this mandatory requirement of minimum of 3 tokens, this could help me in modifying the logic to suit for my objective.
Thank you

**Comment by susantabiswas** [comment]
@ShrikanthSingh Don't remember for sure, but I think it was because of the usage of trigrams and higher n-grams.

**Comment by ShrikanthSingh** [comment]
> @ShrikanthSingh Don't remember for sure, but I think it was because of the usage of trigrams and higher n-grams.

Hey Susant, Thank you for your immediate reply anyways I found a small hack to solve this limitation.
